### ISSUE TITLE
v2022.4.4 still requires homeassistant 2022.4.2 in some places

### ISSUE THREAD

**Issue by graham33** [KapJI/homeassistant-stubs#163]
FYI.  For example https://github.com/KapJI/homeassistant-stubs/blob/2022.4.4/pyproject.toml#L27, and also in `poetry.lock`.  Thanks!

**Comment by KapJI** [comment]
For some reason automation didn't update it. But as I can see only `2022.4.3` and `2022.4.4` were affected.
