### ISSUE TITLE
Syntax errors in generated stubs

### ISSUE THREAD

**Issue by graham33** [KapJI/homeassistant-stubs#238]
Hi there,

I've noticed this problem in recent versions:

```
/nix/store/cm7xda19nh3bb326y5qv56750ni3dz49-python3.10-homeassistant-stubs-2022.10.4/lib/python3.10/site-packages/homeassistant-stubs/components/bluetooth/models.pyi:27: error: invalid syntax
Found 1 error in 1 file (errors prevented further checking)                   
```

This appears to be due to https://github.com/python/mypy/issues/12441, so not really a bug in this project (hence feel free to just close the issue), but I thought I should note it.

I managed to work around it with the following hacky sed commands on the installed `.pyi` files:

```
find $out -name "*.pyi" -print0 | xargs -0 sed -i 's/, \*,/, *args,/g'                                                                                                                                                            
find $out -name "*.pyi" -print0 | xargs -0 sed -i 's/, \*\*)/, **kwargs)/g'    
```

**Comment by KapJI** [comment]
`*` is actually legit separator for keyword-only arguments, see: [PEP 3102](https://peps.python.org/pep-3102/).

Nameless `kwargs` is wrong but there are only 3 places right now:
- `components/unifi/update.pyi`
- `components/unifiprotect/text.pyi`
- `components/zwave_js/humidifier.pyi`
