### ISSUE TITLE
Check installation on Windows

### ISSUE THREAD

**Issue by mdeweerd** [KapJI/homeassistant-stubs#284]
FYI, when I try to use the current packages on a windows Python 3.11 installation, I run into the issue that aiohttp==3.8.1 requires compilation that does "fails".
I can install 3.7.4,3.8.2,3.8.3 but not 3.8.0 or 3.8.1

**Comment by mdeweerd** [comment]
I reverted to Python 3.10 where aiohttp-3.8.1 could be installed and added a change in the ci.yml setup..

**Comment by KapJI** [comment]
This project doesn't depend on aiohttp directly, so this seem unrelated. There's a chance some other project doesn't set its dependencies correctly or more likely it's host specific issue.

I guess Python 3.11 isn't supported yet but some dependencies.
